=== CodeGod313/ThirdTask/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/medicines"
        xmlns:tns="http://www.example.org/medicines"
        elementFormDefault="qualified">
    <element name="medicines">
        <complexType>
            <sequence>
                <element ref="tns:medicine" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="medicine">
        <sequence>
            <element name="name" type="string"/>
            <element name="pharm" type="string"/>
            <element name="group" type="tns:group"/>
            <element name="analogs" type="tns:analogs"/>
            <element name="versions" type="tns:versions"/>
            <element name="certificate" type="tns:certificate"/>
            <element name="package" type="tns:dosage"/>
        </sequence>
        <attribute name="id" type="tns:medicineID" use="required"/>
        <attribute name="pharm-website"/>
    </complexType>

    <simpleType name="medicineID">
        <restriction base="ID">
            <pattern value="\w{1,100}"/>
        </restriction>
    </simpleType>

    <simpleType name="group">
        <restriction base="string">
            <enumeration value="antibiotic"/>
            <enumeration value="pain-killer"/>
            <enumeration value="vitamin"/>
            <enumeration value="antipyretic"/>
        </restriction>
    </simpleType>

    <complexType name="analogs">
        <sequence>
            <element name="analog" type="string" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <simpleType name="versions">
        <restriction base="string">
            <enumeration value="pills"/>
            <enumeration value="capsules"/>
            <enumeration value="powder"/>
            <enumeration value="drops"/>
        </restriction>
    </simpleType>

    <complexType name="certificate">
        <sequence>
            <element name="number" type="positiveInteger"/>
            <element name="date-of-issue" type="date"/>
            <element name="expiration-date" type="date"/>
            <element name="registering-organisation" type="string"/>
        </sequence>
    </complexType>

    <complexType name="package">
        <sequence>
            <element name="type" type="tns:type-of-package"/>
            <element name="count" type="positiveInteger"/>
            <element name="price" type="positiveInteger"/>
        </sequence>
    </complexType>

    <simpleType name="type-of-package">
        <restriction base="string">
            <enumeration value="box"/>
            <enumeration value="pill-plate"/>
            <enumeration value="bottle"/>
        </restriction>
    </simpleType>

    <complexType name="dosage">
        <sequence>
            <element name="period" type="positiveInteger"/>
            <element name="dose" type="tns:dose"/>
        </sequence>
    </complexType>

    <simpleType name="dose">
        <restriction base="string">
            <pattern value="\d+\s(pills|drops|capsules)"/>
        </restriction>
    </simpleType>
    <!--description of medicines inherited from tns:medicine-->
    <complexType name="human-medicine">
        <complexContent>
            <extension base="tns:medicine">
                <sequence>
                    <element name="age" type="tns:age"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="age">
        <restriction base="string">
            <enumeration value="children"/>
            <enumeration value="adult"/>
        </restriction>
    </simpleType>

    <complexType name="veterinaryMedicine">
        <complexContent>
            <extension base="tns:medicine">
                <sequence>
                    <element name="type-of-animal" type="tns:type-of-animal"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="type-of-animal">
        <restriction base="string">
            <enumeration value="dog"/>
            <enumeration value="cat"/>
            <enumeration value="horse"/>
            <enumeration value="chicken"/>
        </restriction>
    </simpleType>
    <!--Substitution group-->
    <element name="medicine" type="tns:medicine" abstract="true"/>
    <element name="human-medicine" type="tns:human-medicine" substitutionGroup="tns:medicine"/>
    <element name="veterinaryMedicine" type="tns:veterinaryMedicine" substitutionGroup="tns:medicine"/>
</schema>

=== CodeGod313/ThirdTask/xml/medicinesTest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.example.org/medicines"
           xsi:schemaLocation="http://www.example.org/medicines ../src/main/resources/schema/schema.xsd">
    <human-medicine id="m1" pharm-website="kakaka.com">
        <name>Pilecium</name>
        <pharm>Human Labs</pharm>
        <group>antibiotic</group>
        <analogs>
            <analog>Signecium</analog>
            <analog>Filecium</analog>
            <analog>Stroncium</analog>
        </analogs>
        <versions>pills</versions>
        <certificate>
            <number>123</number>
            <date-of-issue>2020-09</date-of-issue>
            <expiration-date>2021-10</expiration-date>
            <registering-organisation>Pharmacuticals Inc.</registering-organisation>
        </certificate>
        <package>
            <type>pill-plate</type>
            <count>22</count>
            <price>187</price>
        </package>
        <dosage>
            <period>16</period>
            <dose>3 pills</dose>
        </dosage>
        <age>adult</age>
    </human-medicine>
</medicines>

=== CodeGod313/ThirdTask/src/main/resources/xml/medicines.xml
<?xml version="1.0" encoding="UTF-8" ?>
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.example.org/medicines"
           xsi:schemaLocation="http://www.example.org/medicines ../schema.xsd">
    <human-medicine id="m1">
        <name>Pilecium</name>
        <pharm>Human Labs</pharm>
        <group>antibiotic</group>
        <analogs>
            <analog>Signecium</analog>
            <analog>Filecium</analog>
            <analog>Stroncium</analog>
        </analogs>
        <versions>pills</versions>
        <certificate>
            <number>123</number>
            <date-of-issue>2020-09-04</date-of-issue>
            <expiration-date>2021-10-22</expiration-date>
            <registering-organisation>Pharmacuticals Inc.</registering-organisation>
        </certificate>
        <package>
            <period>12</period>
            <dose>2 pills</dose>
        </package>
        <age>adult</age>
    </human-medicine>

    <veterinaryMedicine id="m2">
        <name>Dogium</name>
        <pharm>AmazingLabs</pharm>
        <group>pain-killer</group>
        <analogs>
            <analog>Paladium</analog>
            <analog>Lopatium</analog>
        </analogs>
        <versions>capsules</versions>
        <certificate>
            <number>7654</number>
            <date-of-issue>2021-12-31</date-of-issue>
            <expiration-date>2023-12-22</expiration-date>
            <registering-organisation>"World Health Assembly</registering-organisation>
        </certificate>
        <package>
            <period>24</period>
            <dose>3 capsules</dose>
        </package>
        <type-of-animal>dog</type-of-animal>
    </veterinaryMedicine>
</medicines>
